services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-net
    env_file:
      - .env
  
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    depends_on:
      - scheduler
    ports:
      - "15672:15672"
      - "5672:5672"
    env_file:
      - .env
    networks:
      - app-net
    
  scheduler:
    build: ./scheduler
    depends_on:
      - mongo
    networks:
      - app-net
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1

volumes:
  mongo-data:

networks:
  app-net: